# Generated by Django 3.2.5 on 2021-09-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20210909_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='member', max_length=50),
        ),
    ]
