# Generated by Django 3.2.5 on 2021-09-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='project_completed',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
