# Generated by Django 3.2.5 on 2021-09-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_projectdata_project_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(default='Next Group Meeting', max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Setting up the date for next group meeting', max_length=200)),
                ('agenda', models.TextField(default='Setup next meeting')),
            ],
        ),
    ]
