# Generated by Django 3.2.5 on 2021-09-29 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_meetings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 29, 17, 2, 33, 536556)),
        ),
    ]
