# Generated by Django 3.2.5 on 2021-09-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_alter_meetings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
