# Generated by Django 3.2.5 on 2021-10-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_alter_meetings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
