# Generated by Django 3.2.5 on 2021-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_meetings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
