# Generated by Django 3.2.5 on 2021-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_auto_20211001_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
