# Generated by Django 3.2.5 on 2021-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.CharField(default='random@random.com', max_length=200),
        ),
        migrations.AddField(
            model_name='profiles',
            name='name',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.CharField(default='admin', max_length=40),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='deadline',
            field=models.DateField(default=('2021', '9', '15')),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='description',
            field=models.CharField(default='Setup next meeting', max_length=200),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='members',
            field=models.CharField(default='Team', max_length=500),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='name',
            field=models.CharField(default='Next meeting', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='owner',
            field=models.CharField(default='secretary', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='start_date',
            field=models.DateField(default=('2021', '9', '6')),
        ),
    ]
