# Generated by Django 3.2.5 on 2021-09-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210906_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='deadline',
            field=models.CharField(default='2021/9/15', max_length=12),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='start_date',
            field=models.CharField(default='2021/9/6', max_length=12),
        ),
    ]
