# Generated by Django 3.2.5 on 2021-09-07 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210906_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='deadline',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
