# Generated by Django 3.2.5 on 2021-09-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_projectdata_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='members',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='owner',
        ),
    ]
