# Generated by Django 3.2.5 on 2021-09-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210907_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='project_name',
        ),
    ]
